SFSAcademy/SFSAcademy/Controllers/BATCHController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SFSAcademy;
using PagedList;
using SFSAcademy.Models;
using System.Web.UI;

namespace SFSAcademy.Controllers
{
    public class BATCHController : Controller
    {
        private SFSAcademyEntities db = new SFSAcademyEntities();

        // GET: BATCH
        public ActionResult Index()
        {
            var bATCHes = db.BATCHes.Include(b => b.COURSE);
            return View(bATCHes.ToList());
        }

        // GET: Batches
        public ActionResult ManageBatches()
        {
            List<SelectListItem> options = new SelectList(db.COURSEs.OrderBy(x => x.ID), "ID", "CRS_NAME").ToList();
            //add the 'ALL' option
            options.Insert(0, new SelectListItem() { Value = "-1", Text = "ALL" });
            ViewBag.searchString = options;
            return View();
        }

        // GET: Fee Index
        public ActionResult _Update_Batch(string sortOrder, string currentFilter, string searchString, int? page)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewBag.DateSortParm = sortOrder == "Date" ? "date_desc" : "Date";

            if (searchString != null && !searchString.Equals("-1"))
            {
                page = 1;
                ///As Drop down list sends Id, we will ahve to convert this to text which is different from text box
                int searchStringId = Convert.ToInt32(searchString);
                searchString = db.COURSEs.Find(searchStringId).CODE.ToString();
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;

            var CourseBatchS = (from cs in db.COURSEs
                                join bt in db.BATCHes on cs.ID equals bt.CRS_ID 
                                where cs.IS_DEL.Equals("N") && bt.IS_DEL.Equals("N")
                                orderby cs.CODE
                                select new Models.CoursesBatch { CourseData = cs, BatchData = bt}).Distinct();

            if (!String.IsNullOrEmpty(searchString) && !searchString.Equals("ALL"))
            {
                CourseBatchS = CourseBatchS.Where(s => s.CourseData.CODE.Contains(searchString));
            }
            switch (sortOrder)
            {
                case "name_desc":
                    CourseBatchS = CourseBatchS.OrderByDescending(s => s.BatchData.NAME);
                    break;
                case "Date":
                    CourseBatchS = CourseBatchS.OrderBy(s => s.BatchData.START_DATE);
                    break;
                case "date_desc":
                    CourseBatchS = CourseBatchS.OrderByDescending(s => s.BatchData.START_DATE);
                    break;
                default:  // Name ascending 
                    CourseBatchS = CourseBatchS.OrderBy(s => s.BatchData.NAME);
                    break;
            }

            int pageSize = 50;
            int pageNumber = (page ?? 1);
            return View(CourseBatchS.ToPagedList(pageNumber, pageSize));
        }

        // GET: BATCH/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BATCH bATCH = db.BATCHes.Find(id);
            if (bATCH == null)
            {
                return HttpNotFound();
            }
            return View(bATCH);
        }

        // GET: BATCH/Create
        public ActionResult Create()
        {
            ViewBag.CRS_ID = new SelectList(db.COURSEs, "ID", "CRS_NAME");
            ViewBag.EMP_ID = new SelectList(db.EMPLOYEEs, "ID", "EMP_NUM");
            return View();
        }

        // POST: BATCH/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,NAME,CRS_ID,START_DATE,END_DATE,IS_DEL,EMP_ID")] BATCH bATCH)
        {
            if (ModelState.IsValid)
            {
                bATCH.IS_DEL = "N";
                bATCH.EMP_ID = Convert.ToInt32(this.Session["UserId"]);
                db.BATCHes.Add(bATCH);
                db.SaveChanges();
                return RedirectToAction("ManageBatches");
            }

            ViewBag.CRS_ID = new SelectList(db.COURSEs, "ID", "CRS_NAME", bATCH.CRS_ID);
            return View(bATCH);
        }

        // GET: BATCH/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BATCH bATCH = db.BATCHes.Find(id);
            if (bATCH == null)
            {
                return HttpNotFound();
            }
            ViewBag.CRS_ID = new SelectList(db.COURSEs, "ID", "CRS_NAME", bATCH.CRS_ID);
            return View(bATCH);
        }

        // POST: BATCH/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,NAME,CRS_ID,START_DATE,END_DATE,IS_DEL,EMP_ID")] BATCH bATCH)
        {
            if (ModelState.IsValid)
            {
                db.Entry(bATCH).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("ManageBatches");
            }
            ViewBag.CRS_ID = new SelectList(db.COURSEs, "ID", "CRS_NAME", bATCH.CRS_ID);
            return View(bATCH);
        }

        // GET: BATCH/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BATCH bATCH = db.BATCHes.Find(id);
            if (bATCH == null)
            {
                return HttpNotFound();
            }
            return View(bATCH);
        }

        // POST: BATCH/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            BATCH bATCH = db.BATCHes.Find(id);
            db.BATCHes.Remove(bATCH);
            db.SaveChanges();
            return RedirectToAction("ManageBatches");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SFSAcademy/SFSAcademy/Controllers/CoursesController.cs
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using PagedList;
using System.Web.UI.WebControls;
using System;
using SFSAcademy.Models;
using SFSAcademy.HtmlHelpers;
using System.Collections.Generic;
using System.Web;
using System.Data;
using System.IO;

namespace SFSAcademy.Controllers
{
    public class CoursesController : Controller
    {
        private SFSAcademyEntities db = new SFSAcademyEntities();

        // GET: Courses
        public ActionResult Index()
        {
            return View();
        }

        // GET: Courses
        public ActionResult ManageCourse()
        {
            return View(db.COURSEs.Where(s=> s.IS_DEL == "N").ToList());
        }
        // GET: Courses/Details/5

        // GET: Courses
        public ActionResult ManageBatches()
        {
            return View(db.BATCHes.ToList());
        }
        // GET: Courses/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            COURSE cOURSE = db.COURSEs.Find(id);
            if (cOURSE == null)
            {
                return HttpNotFound();
            }
            return View(cOURSE);
        }

        // GET: Courses/Create
        public ActionResult Create()
        {

            DateTime PDate = Convert.ToDateTime(System.DateTime.Now);
            ViewBag.ReturnDate = PDate.ToShortDateString();
            DateTime PDate2 = Convert.ToDateTime(System.DateTime.Now.AddYears(1));
            ViewBag.ReturnDate2 = PDate2.ToShortDateString();
            ViewBag.BATCH_NAME = "";
            var GradingLevelList = new SelectList(new[]
        {
                        new { ID = "Normal", Name = "Normal" },
                        new { ID = "GPA", Name = "GPA" },
                        new { ID = "CWA", Name = "CWA" },
                        new { ID = "CCE", Name = "CCE" },
                        new { ID = "ICSE", Name = "ICSE" },
                    },
                "ID", "Name", "Normal");

            ViewData["GRADING_TYPE"] = GradingLevelList;


            return View();
        }

        // POST: Courses/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,CRS_NAME,CODE,SECTN_NAME,IS_DEL,CREATED_AT,UPDATED_AT,GRADING_TYPE")] COURSE cOURSE, string BATCH_NAME, DateTime ReturnDate, DateTime ReturnDate2)
        {
            if (ModelState.IsValid)
            {
                cOURSE.IS_DEL = "N";
                cOURSE.CREATED_AT = System.DateTime.Now;
                cOURSE.UPDATED_AT = System.DateTime.Now;
                db.COURSEs.Add(cOURSE);
                db.SaveChanges();

                BATCH bATCH = new BATCH();
                bATCH.NAME = BATCH_NAME;
                bATCH.START_DATE = ReturnDate;
                bATCH.END_DATE = ReturnDate2;
                bATCH.CRS_ID = cOURSE.ID;
                bATCH.IS_DEL = "N";
                db.BATCHes.Add(bATCH);
                db.SaveChanges();
                ViewBag.Message = "Course created successfully!";

                DateTime PDate = Convert.ToDateTime(ReturnDate);
                ViewBag.ReturnDate = PDate.ToShortDateString();
                DateTime PDate2 = Convert.ToDateTime(ReturnDate2);
                ViewBag.ReturnDate2 = PDate2.ToShortDateString();
                ViewBag.BATCH_NAME = BATCH_NAME;
                var GradingLevelList = new SelectList(new[]
            {
                        new { ID = "Normal", Name = "Normal" },
                        new { ID = "GPA", Name = "GPA" },
                        new { ID = "CWA", Name = "CWA" },
                        new { ID = "CCE", Name = "CCE" },
                        new { ID = "ICSE", Name = "ICSE" },
                    },
                    "ID", "Name", "Normal");

                ViewData["GRADING_TYPE"] = GradingLevelList;
                return View();
            }

            ViewBag.Message = "There is some issue adding course.";
            return View(cOURSE);
        }

        // GET: Courses/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            COURSE cOURSE = db.COURSEs.Find(id);
            if (cOURSE == null)
            {
                return HttpNotFound();
            }
            return View(cOURSE);
        }

        // POST: Courses/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,CRS_NAME,CODE,SECTN_NAME,IS_DEL,CREATED_AT,UPDATED_AT,GRADING_TYPE")] COURSE cOURSE)
        {
            if (ModelState.IsValid)
            {
                db.Entry(cOURSE).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(cOURSE);
        }

        // GET: Courses/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            COURSE cOURSE = db.COURSEs.Find(id);
            if (cOURSE == null)
            {
                return HttpNotFound();
            }
            return View(cOURSE);
        }

        // POST: Courses/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            var BatchVal = (from C in db.BATCHes
                               where C.CRS_ID == id
                               select new { C}).ToList();

            /*var GuardianVal = (from C in db.GUARDIANs
                               where C.WARD_ID == Std_id
                               select new Models.SelectGuardian { GuardianList = C }).ToList();

            return View(GuardianVal);*/

            if(BatchVal.Count.Equals(0))
            {
                COURSE cOURSE = db.COURSEs.Find(id);
                cOURSE.IS_DEL = "Y";
                cOURSE.UPDATED_AT = System.DateTime.Now;
                db.Entry(cOURSE).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("ManageCourse");
            }
            else
            {
                ViewBag.Message = "Batch related to this course needs to be deleted first!";
                return View();
            }

        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SFSAcademy/SFSAcademy/Views/Courses/Create.cshtml
@model SFSAcademy.COURSE

@{
    ViewBag.Title = "Course_New";
}
<script type="text/javascript" src="@Url.Content("~/Content/javascripts/jquery/jquery.min.js")"></script>
<script type="text/javascript" src="@Url.Content("~/Content/javascripts/jquery/jquery-ui.min.js")"></script>
<script type="text/javascript" src="@Url.Content("~/Content/javascripts/jquery/jquery-1.9.1.js")"></script>
<script type="text/javascript" src="@Url.Content("~/Content/javascripts/jquery/jquery-ui.js")"></script>
<link rel="stylesheet" href="~/Content/stylesheets/_styles/jquery-ui.css" />
<script>
    $(function () {
        $("#datepicker").datepicker({
            showOn: "button",
            buttonImage: "/Content/images/calendar_date_select/calendar.gif",
            dateFormat: 'dd-mm-yy',
            buttonImageOnly: true
        });
        $("#datepicker2").datepicker({
            showOn: "button",
            buttonImage: "/Content/images/calendar_date_select/calendar.gif",
            dateFormat: 'dd-mm-yy',
            buttonImageOnly: true
        });
    });

</script>
<div id="content-header">
    <img src="~/Content/images/examination/show_exam.png" alt="Settings Logo">
    <h1>Courses</h1>
    <h3>New</h3>
    <div id="app-back-button">
        <a href='javascript:history.back()' onclick="return confirm('are you sure?')"><img src="~/Content/images/buttons/back.png"></a>
    </div>
</div>
<div><img src="~/Content/images/_global/header_underline_.jpg" width="100%"></div>

<div id="page-yield">
    <div class="bread_crumb">
        <a href="@Url.Action("Index", "Configuration")">Configuration</a> &raquo;
        <a href="@Url.Action("Index", "Courses")">Courses</a> &raquo;
        <a href="@Url.Action("ManageCourse", "Courses")">Manage Course</a> &raquo;
        New
    </div>

    @if (ViewBag.Message != null)
    {
        <p class="flash-msg"> @ViewBag.Message </p>
    }

    <div id="grading-levels-form">
        <div class="bread_crumb">
            <a href="@Url.Action("ManageCourse", "Courses")">Course</a> &raquo;
            New
        </div>
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="label-field-pair">
                <div class="label-container">@Html.LabelFor(model => model.CRS_NAME, "Course Name", htmlAttributes: new { @class = "control-label col-md-2" })</div>               
                <div class="input-container">
                    @Html.EditorFor(model => model.CRS_NAME, new { htmlAttributes = new { @class = "form-control", required = "required" } })
                    <span class="necessary-field" style="font-size:small">* Required Field</span>
                    @Html.ValidationMessageFor(model => model.CRS_NAME, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="label-field-pair">
                <div class="label-container">@Html.LabelFor(model => model.SECTN_NAME, "Section Name", htmlAttributes: new { @class = "control-label col-md-2" })</div>
                <div class="input-container">
                    @Html.EditorFor(model => model.SECTN_NAME, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.SECTN_NAME, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="label-field-pair">
                <div class="label-container">@Html.LabelFor(model => model.CODE, "Course Code", htmlAttributes: new { @class = "control-label col-md-2" })</div>
                <div class="input-container">
                    @Html.EditorFor(model => model.CODE, new { htmlAttributes = new { @class = "form-control", required = "required" } })
                    <span class="necessary-field" style="font-size:small">* Required Field</span>
                    @Html.ValidationMessageFor(model => model.CODE, "", new { @class = "text-danger" })
                </div>
            </div>
            <div id="grading">
                <div class="label-field-pair">
                    <div class="label-container">@Html.LabelFor(model => model.GRADING_TYPE, "Grading system type", htmlAttributes: new { @class = "control-label col-md-2" })</div>
                    <div class="text-input-bg">
                        @Html.DropDownList("GRADING_TYPE", ViewData["GRADING_TYPE"] as SelectList, htmlAttributes: new { @class = "GRADING_TYPE", @onChange = "SelectAddType(this.value)", id = "GRADING_TYPE" })
                        @Html.ValidationMessageFor(model => model.GRADING_TYPE, "", new { @class = "text-danger" })
                        @Html.HiddenFor(model => model.GRADING_TYPE)
                    </div>
                </div>
            </div>
            <h4>Initial Batch Details</h4>
            <div class="label-field-pair">
                <div class="label-container">@Html.Label("BATCH_NAME", "Name", htmlAttributes: new { @class = "control-label col-md-2" })</div>
                <div class="input-container">
                    @Html.Editor("BATCH_NAME", new { htmlAttributes = new { @class = "form-control" } })
                </div>
            </div>

            <div class="label-field-pair">
                <div class="label-container">@Html.Label("ReturnDate", "Start Date", htmlAttributes: new { @class = "control-label col-md-2" })</div>
                <div class="input-container">
                    @Html.Editor("ReturnDate", new { htmlAttributes = new { @class = "form-control", @id = "datepicker", @Value = ViewBag.ReturnDate, @readonly = "readonly" } })
                </div>
            </div>
            <div class="label-field-pair">
                <div class="label-container">@Html.Label("ReturnDate2", "End Date", htmlAttributes: new { @class = "control-label col-md-2" })</div>
                <div class="input-container">
                    @Html.Editor("ReturnDate2", new { htmlAttributes = new { @class = "form-control", @id = "datepicker2", @Value = ViewBag.ReturnDate2, @readonly = "readonly" } })
                </div>
            </div>
            <div id="submit_area">
                <input type="submit" value="► Save" class="submit_button" />
            </div>
            <div class="extender"></div>
        }

    </div>
</div>
<script type="text/javascript">
  function toggle_grading(){
    if($('course_cce_enabled').checked){
      $("grading").hide();
      $('course_grading_type').value="Normal"
    }
    else{
      $("grading").show();
    }
    return true;
  }
@section scripts{

    @Scripts.Render("~/bundles/jqueryval")

    <script src="~/Scripts/dropzone.js"></script>

<script type="text/javascript">

$(document).ready(function () {
    $("#preview").fadeOut(15);
    $("#refreshButton").click(function () {
        var imageToLoad = $("#imageId").val();
        if (imageToLoad.length > 0) {
            $("#preview").attr("src", "/Document/Show/" + imageToLoad);
            $("#preview").fadeIn();
        }
    });
});

</script>
}

SFSAcademy/SFSAcademy/Views/Courses/Delete.cshtml
@model SFSAcademy.COURSE

@{
    ViewBag.Title = "Delete";
}

<div id="content-header">
    <img src="~/Content/images/show_settings.png" alt="Settings Logo">
    <h1>Delete Courses</h1>
    <h3>Manage Course</h3>
    <div id="app-back-button">
        <a href='javascript:history.back()' onclick="return confirm('are you sure?')"><img src="~/Content/images/buttons/back.png"></a>
    </div>
</div>
<div><img src="~/Content/images/_global/header_underline_.jpg" width="100%"></div>

<h3>Are you sure you want to delete this?</h3>
<div id="page-yield">
    <div class="bread_crumb">
        <a href="@Url.Action("Index", "Configuration")">Configuration</a> &raquo;
        <a href="@Url.Action("Index", "Courses")">Courses</a> &raquo;
        Manage Course
    </div>
    @if (ViewBag.Message != null)
    {
        <p class="flash-msg"> @ViewBag.Message </p>
    }
    <div id="edit_user_form">
        <div class="label-field-pair">
            @Html.LabelFor(model => model.CRS_NAME, "Course Name", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="text-input-bg">
                @Html.EditorFor(model => model.CRS_NAME, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CRS_NAME, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="label-field-pair">
            @Html.LabelFor(model => model.CODE, "Course Code", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="text-input-bg">
                @Html.EditorFor(model => model.CODE, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CODE, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="label-field-pair">
            @Html.LabelFor(model => model.SECTN_NAME, "Section Name", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="text-input-bg">
                @Html.EditorFor(model => model.SECTN_NAME, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SECTN_NAME, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="label-field-pair">
            @Html.LabelFor(model => model.GRADING_TYPE, "Grading Type", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="text-input-bg">
                @Html.EditorFor(model => model.GRADING_TYPE, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.GRADING_TYPE, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "ManageCourse")
        </div>
    }

</div>



SFSAcademy/SFSAcademy/Views/Courses/Details.cshtml
@model SFSAcademy.COURSE

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>COURSE</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CRS_NAME)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CRS_NAME)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CODE)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CODE)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SECTN_NAME)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SECTN_NAME)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IS_DEL)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IS_DEL)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CREATED_AT)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CREATED_AT)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UPDATED_AT)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UPDATED_AT)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GRADING_TYPE)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GRADING_TYPE)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }, new { style = "text-decoration:underline" }) |
    @Html.ActionLink("Back to List", "Index", null, new { style = "text-decoration:underline" })
</p>

SFSAcademy/SFSAcademy/Views/Courses/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<div id="content-header">
    <img src="~/Content/images/show_settings.png" alt="Settings Logo">
    <h1>Courses</h1>
    <h3>Home</h3>
    <div id="app-back-button">
        <a href='javascript:history.back()' onclick="return confirm('are you sure?')"><img src="~/Content/images/buttons/back.png"></a>
    </div>
</div>
<div><img src="~/Content/images/_global/header_underline_.jpg" width="100%"></div>

<div id="page-yield">
    <div class="box">
        <div class="link-box">
            <div class="link-heading">@Html.ActionLink("Manage Course", "ManageCourse")</div>
            <div class="link-descr">Manage Course and create batches</div>
        </div>
        <div class="link-box">
            <div class="link-heading"><a href="@Url.Action("ManageBatches", "BATCH")">Manage Batch </a></div>
            <div class="link-descr">Manage active batches</div>
        </div>
        <div class="extender"></div>
    </div>
</div>

SFSAcademy/SFSAcademy/Views/Courses/ManageCourse.cshtml
@model IEnumerable<SFSAcademy.COURSE>

@{
    ViewBag.Title = "ManageCourse";
}


<div id="content-header">
    <img src="~/Content/images/show_settings.png" alt="Settings Logo">
    <h1>Courses</h1>
    <h3>Manage Course</h3>
    <div id="app-back-button">
        <a href='javascript:history.back()' onclick="return confirm('are you sure?')"><img src="~/Content/images/buttons/back.png"></a>
    </div>
</div>
<div><img src="~/Content/images/_global/header_underline_.jpg" width="100%"></div>
<div id="inner-tab-menu">
    <ul>
        <li>@Html.ActionLink("New", "Create")</li>
    </ul>
</div>
<div id="page-yield">
    <div class="bread_crumb">
        <a href="@Url.Action("Index", "Configuration")">Configuration</a> &raquo;
        <a href="@Url.Action("Index", "Courses")">Courses</a> &raquo;
        Manage Course
    </div>
    @if (ViewBag.Message != null)
    {
        <p class="flash-msg"> @ViewBag.Message </p>
    }
    <div class="box">
        <h4 align="center">Course</h4>
        <table id="listing" align="center" width="100%" cellpadding="1" cellspacing="1">
            @{int i = 1; }
            @foreach (var item in Model)
            {
                string selectedRow = "tr-even";
                if (i % 2 == 0)
                {
                    selectedRow = "tr-odd";
                }
                <tr class="@selectedRow">
                    <td>
                        @Html.DisplayFor(modelItem => item.CRS_NAME)
                    </td>
                    <td>
                        <span>   </span>
                        <span>   </span>
                    </td>
                    <td>
                        @Html.ActionLink("Edit", "Edit", new { id = item.ID }, new { style = "text-decoration:underline" }) |
                        @Html.ActionLink("Delete", "Delete", new { id = item.ID }, new { style = "text-decoration:underline" })
                    </td>
                </tr>
                i = i + 1;
            }
        </table>
        <div class="extender"></div>
    </div>
</div>