SFSAcademy/SFSAcademy/Models/News.cs
using System;
using System.Data;
using System.Linq;
using System.Web.UI.WebControls;
using System.ComponentModel.DataAnnotations;
using System.Collections.Generic;
using SFSAcademy.Helpers;
using System.Web.Mvc;

namespace SFSAcademy.Models
{
    //public class NewsMaster
    //{
    //    public NEWS NewsData { get; set; }
    //    public NEWS_COMMENTS NewsCommentData { get; set; }
    //    public USER userData { get; set; }
    //}

    public class NewsComments
    {
        public int commentId { get; set; }
        public int? newsId { get; set; }
        public string commentContent { get; set; }
        public string commentAddedBy { get; set; }
        public int? AddedByUserId { get; set; }
        public DateTime? commentAddedDate { get; set; }
        public DateTime? commentUpdatedDate { get; set; }
        public string isApproved { get; set; }
        public string EnableNewsCommentModeration { get; set; }
        public User Author { get; set; }

        public void reload_news_bar()
        {
            //ActionHelper.expire_fragment(cache_fragment_name());
            News nw = new News();
            DataTable dt = nw.Get_Latest();
        }

        public string cache_fragment_name()
        {
            return "News_latest_fragment";
        }

    }

    public class NewsDetails
    {
        public int newsId { get; set; }
        [Required]
        [Display(Name = "News Title")]
        public string newsTitle { get; set; }
        [Required]
        [Display(Name = "News Content")]
        public string newsContent { get; set; }
        public DateTime? newsCreatedDate { get; set; }
        public DateTime? newsUpdatedDate { get; set; }
        [Display(Name = "Author of this News")]
        public string newsCreatedBy { get; set; }
        public int newsCommentCount { get; set; }
        public List<NewsComments> commentList { get; set; }
        public string isUserAdmin { get; set; }
        public string isModerator { get; set; }
        public int? CreatedByUserId { get; set; }
        public double days { get; set; }
        public string newsComment { get; set; }

        public User Author { get; set; }

        public void reload_news_bar()
        {
            //ActionHelper.expire_fragment(cache_fragment_name());
            News nw = new News();
            DataTable dt = nw.Get_Latest();
        }

        public string cache_fragment_name()
        {
            return "News_latest_fragment";
        }
    }
    public class News
    {
        private SFSAcademyEntities db = new SFSAcademyEntities();
        [Required]
        [Display(Name = "News Title")]
        public string Title { get; set; }

        [Required]
        [Display(Name = "News Content")]
        public string Content { get; set; }

        [Display(Name = "Author of this News")]
        public bool Author { get; set; }

        /// <summary>
        /// Checks if user with given password exists in the database
        /// </summary>
        /// <param name="_username">User name</param>
        /// <param name="_password">User password</param>
        /// <returns>True if user exist and password is correct</returns>

        [OutputCache(Duration = 10, VaryByParam = "*")]
        public DataTable Get_Latest()
        {
            var LatestNews = new DataTable();

            LatestNews.Columns.Add("Id", typeof(int));
            LatestNews.Columns.Add("NewsTitle", typeof(string));
            LatestNews.Columns.Add("NewsContent", typeof(string));
            LatestNews.Columns.Add("NewsDate", typeof(DateTime));

            var News = (from EV in db.NEWS
                        orderby EV.CREATED_AT descending
                        select new { ID = EV.ID, TITLE = EV.TIL, CONTENT = EV.CNTNT, DATE = EV.CREATED_AT }).Take(3);

            foreach (var entity in News.ToList())
            {
                var row = LatestNews.NewRow();
                row["Id"] = entity.ID;
                row["NewsTitle"] = entity.TITLE;
                row["NewsContent"] = entity.CONTENT;
                row["NewsDate"] = entity.DATE;
                LatestNews.Rows.Add(row);
            }
            return LatestNews;

        }
    }
}

SFSAcademy/SFSAcademy/Controllers/newsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;
using SFSAcademy.Models;
using System.Net;
using System.Data.Entity;

namespace SFSAcademy.Controllers
{
    public class newsController : Controller
    {
        private SFSAcademyEntities db = new SFSAcademyEntities();

        // GET: News
        public ActionResult Index(string sortOrder, string currentFilter, string searchString, int? page)
        {
            int UserId = Convert.ToInt32(this.Session["UserId"]);
            ViewBag.CurrentSort = sortOrder;
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewBag.DateSortParm = sortOrder == "Date" ? "date_desc" : "Date";

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;

            var News = (from nw in db.NEWS
                        join us in db.USERS on nw.AUTH_ID equals us.ID into uj
                        from subus in uj.DefaultIfEmpty()
                        orderby nw.UPDATED_AT
                        select new Models.NewsDetails
                        {
                            newsId = nw.ID,
                            CreatedByUserId = (nw.AUTH_ID == null) ? 0 : nw.AUTH_ID,
                            newsTitle = nw.TIL,
                            newsContent = nw.CNTNT,
                            newsCreatedBy = (nw.AUTH_ID == 0) ? "User Deleted" : string.Concat(subus.FIRST_NAME, " ", subus.LAST_NAME, " ", (subus.ADMIN_IND == "Y") ? " - Admin" : ""),
                            newsCreatedDate = nw.CREATED_AT,
                            newsUpdatedDate = nw.UPDATED_AT,
                            newsCommentCount = db.NEWS_COMMENTS.Where(X => X.NEWS_ID == nw.ID && X.IS_APPR == "Y").Distinct().Count(),
                            isUserAdmin = subus.ADMIN_IND,
                            commentList = (from com in db.NEWS_COMMENTS
                                           join us in db.USERS on com.AUTH_ID equals us.ID into gj
                                           from comus in gj.DefaultIfEmpty()
                                           where com.NEWS_ID == nw.ID
                                           orderby com.ID
                                           select new Models.NewsComments
                                           {
                                               commentId = com.ID,
                                               newsId = com.NEWS_ID,
                                               commentContent = com.CNTNT,
                                               commentAddedBy = string.Concat(comus.FIRST_NAME, " ", comus.LAST_NAME),
                                               commentAddedDate = com.CREATED_AT,
                                               commentUpdatedDate = com.UPDATED_AT,
                                               isApproved = com.IS_APPR
                                           }).ToList()
                        }).ToList();

            if (!String.IsNullOrEmpty(searchString))
            {
                News = News.Where(s => s.newsTitle.Contains(searchString)).ToList();
            }

            switch (sortOrder)
            {
                case "title_desc":
                    News = News.OrderByDescending(s => s.newsTitle).ToList();
                    break;
                case "Author":
                    News = News.OrderBy(s => s.newsCreatedBy).ToList();
                    break;
                case "date_desc":
                    News = News.OrderByDescending(s => s.newsCreatedDate).ToList();
                    break;
                default:  // Name ascending 
                    News = News.OrderBy(s => s.newsTitle).ToList();
                    break;
            }

            int pageSize = 10;
            int pageNumber = (page ?? 1);
            return View(News.ToPagedList(pageNumber, pageSize));
        }


        private double GetDayOfAdding(DateTime createddate, DateTime updatedDate)
        {
            double days = 0;
            DateTime actualDate = new DateTime();
            if (updatedDate != null)
                actualDate = updatedDate;
            else
                actualDate = createddate;
            days = (actualDate - System.DateTime.Now).TotalDays;
            DateTime d1 = DateTime.Now;
            DateTime d2 = DateTime.Now.AddDays(-1);

            TimeSpan t = d1 - d2;
            double NrOfDays = t.TotalDays;
            return 0;
        }

        private NewsDetails GetNewsDetails(int id)
        {
            int UserId = Convert.ToInt32(this.Session["UserId"]);
            NewsDetails newsDetail = (from nw in db.NEWS
                                      join us in db.USERS on nw.AUTH_ID equals us.ID into uj
                                      from subus in uj.DefaultIfEmpty()
                                      where nw.ID == id
                                      orderby nw.UPDATED_AT
                                      select new Models.NewsDetails
                                      {
                                          newsId = nw.ID,
                                          CreatedByUserId = (nw.AUTH_ID == null) ? 0 : nw.AUTH_ID,
                                          newsTitle = nw.TIL,
                                          newsContent = nw.CNTNT,
                                          newsCreatedBy = (nw.AUTH_ID == 0) ? "User Deleted" : string.Concat(subus.FIRST_NAME, " ", subus.LAST_NAME, " ", (subus.ADMIN_IND == "Y") ? " - Admin" : ""),
                                          newsCreatedDate = nw.CREATED_AT,
                                          newsUpdatedDate = nw.UPDATED_AT,
                                          newsCommentCount = db.NEWS_COMMENTS.Where(X => X.NEWS_ID == nw.ID && X.IS_APPR == "Y").Distinct().Count(),
                                          isUserAdmin = subus.ADMIN_IND,
                                          isModerator = subus.ADMIN_IND,
                                      }).FirstOrDefault();

            newsDetail.commentList = (from com in db.NEWS_COMMENTS
                                      join us in db.USERS on com.AUTH_ID equals us.ID into gj
                                      from comus in gj.DefaultIfEmpty()
                                      where com.NEWS_ID == id
                                      orderby com.ID
                                      select new Models.NewsComments
                                      {
                                          commentId = com.ID,
                                          newsId = com.NEWS_ID,
                                          commentContent = com.CNTNT,
                                          commentAddedBy = (com.AUTH_ID == 0) ? "User Deleted" : string.Concat(comus.FIRST_NAME, " ", comus.LAST_NAME),
                                          AddedByUserId = com.AUTH_ID,
                                          //commentAddedBy = string.Concat(comus.FIRST_NAME, " ", comus.LAST_NAME),
                                          commentAddedDate = com.CREATED_AT,
                                          commentUpdatedDate = com.UPDATED_AT,
                                          isApproved = com.IS_APPR,
                                          EnableNewsCommentModeration = (from config in db.CONFIGURATIONs
                                                                         where config.CONFIG_KEY == "EnableNewsCommentModeration"
                                                                         select config).FirstOrDefault().CONFIG_VAL
                                      }).ToList();

            return newsDetail;
        }

        public ActionResult view(int id)
        {
            var userdetails = this.Session["CurrentUser"] as UserDetails;
            NewsDetails newsDetail = new NewsDetails();
            int UserId = Convert.ToInt32(this.Session["UserId"]);
            ViewBag.current_user = UserId;
            newsDetail = GetNewsDetails(id);
            ViewBag.isModerator = (userdetails.privilage.Select(p => p.Name == "ManageNews").FirstOrDefault()) ? true : false;
            ViewBag.isAdminUser = (userdetails.ADMIN_IND == "Y") ? true : false;
            return View("view", newsDetail);
        }


        // GET: News/ view All
        public ActionResult all()
        {
            int UserId = Convert.ToInt32(this.Session["UserId"]);
            var News = (from nw in db.NEWS
                        join us in db.USERS on nw.AUTH_ID equals us.ID into uj
                        from subus in uj.DefaultIfEmpty()
                        orderby nw.UPDATED_AT
                        select new Models.NewsDetails
                        {
                            newsId = nw.ID,
                            CreatedByUserId = (nw.AUTH_ID == null) ? 0 : nw.AUTH_ID,
                            newsTitle = nw.TIL,
                            newsContent = nw.CNTNT,
                            newsCreatedBy = (nw.AUTH_ID == 0) ? "User Deleted" : string.Concat(subus.FIRST_NAME, " ", subus.LAST_NAME, " ", (subus.ADMIN_IND == "Y") ? " - Admin" : ""),
                            newsCreatedDate = nw.CREATED_AT,
                            newsUpdatedDate = nw.UPDATED_AT,
                            newsCommentCount = db.NEWS_COMMENTS.Where(X => X.NEWS_ID == nw.ID && X.IS_APPR == "Y").Distinct().Count(),
                            isUserAdmin = subus.ADMIN_IND,
                            commentList = (from com in db.NEWS_COMMENTS
                                           join us in db.USERS on com.AUTH_ID equals us.ID into gj
                                           from comus in gj.DefaultIfEmpty()

SFSAcademy/SFSAcademy/Views/news/Create.cshtml
@model SFSAcademy.NEWS

@{
    ViewBag.Title = "Create";
}

<div id="content-header">
    <img src="~/Content/images/manage_news/manage_news_logo.png" alt="Profile Logo">
    <h1>Add News</h1>
    <h3>Create New News</h3>
    <div id="app-back-button">
        <a href='javascript:history.back()' onclick="return confirm('are you sure?')"><img src="~/Content/images/buttons/back.png"></a>
    </div>
</div>
<div><img src="~/Content/images/_global/header_underline_.jpg" width="100%"></div>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div id="page-yield">
        @if (Html.ValidationSummary() != null)
        {
            <p class="flash-msg"> @Html.ValidationSummary() </p>
        }
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-horizontal">
            <h4>NEWS</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.TIL, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.TIL, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.TIL, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.CNTNT, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.CNTNT, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.CNTNT, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.CREATED_AT, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.CREATED_AT, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.CREATED_AT, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.UPDATED_AT, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.UPDATED_AT, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.UPDATED_AT, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.AUTH_ID, "AUTH_ID", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("AUTH_ID", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.AUTH_ID, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>

    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

SFSAcademy/SFSAcademy/Views/news/Index.cshtml
@model PagedList.IPagedList<SFSAcademy.Models.NewsDetails>
@using SFSAcademy
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />
@{
    ViewBag.Title = "Index";
}

<div id="content-header">
    <img src="~/Content/images/manage_news/manage_news_logo.png" alt="News Logo">
    <h1>School News</h1>
    <h3>Latest announcement</h3>
    <div id="app-back-button">
        <a href='javascript:history.back()' onclick="return confirm('are you sure?')"><img src="~/Content/images/buttons/back.png"></a>
    </div>
</div>
<div><img src="~/Content/images/_global/header_underline_.jpg" style="width:100%"></div>
<div id="inner-tab-menu">
    <ul>
        <li>@Html.ActionLink("View All", "Index")</li>
        <li>@Html.ActionLink("Add New", "add")</li>
    </ul>
</div>

<div id="page-yield">
    <div id="search_add_news_area">
        @if (ViewBag.ErrorMessage != null)
        {
            <p class="flash-msg"> @ViewBag.ErrorMessage </p>
        }
        <div class="news_search_add">
            <div id="news_bg">
                <form name="s1form" action="" style="display:inline;">
                    @using (Html.BeginForm("Index", "news", FormMethod.Get))
                    {
                        <p>
                            @Html.TextBox("SearchString", ViewBag.CurrentFilter as string)
                            <input type="submit" value="go" />
                        </p>
                    }
                </form>
                <div class="extender2"></div>
            </div>
        </div>
        <div class="extender"></div>
    </div>

    @if (Model != null)
    {
        <div id="all_news">
            <table id="listing" align="center" width:"100%" cellpadding="1" cellspacing="1">

                <tr class="tr-head">
                    <td>
                        Sr No
                    </td>
                    <td>
                        Title
                    </td>
                    <td>
                        Author
                    </td>
                    <td>
                        Comments
                    </td>
                    <td>
                        Posted
                    </td>
                </tr>
                <tr class="tr-blank"></tr>
                @{int i = 1; }
                @foreach (var item in Model)
                {
                    string selectedRow = "tr-even";
                    if (i % 2 == 0)
                    {
                        selectedRow = "tr-odd";
                    }
                    <tr class="@selectedRow">
                        <td class="col-1">@i</td>
                        <td class="col-4">
                            @Html.ActionLink(item.newsTitle, "view", new { id = item.newsId })
                        </td>

                        <td class="col-4">
                            @Html.DisplayFor(modelItem => item.newsCreatedBy)
                        </td>

                        @if (item.newsCommentCount != 0)
                        {
                            <td class="col-1">
                                @Html.DisplayFor(modelItem => item.newsCommentCount)
                            </td>
                        }
                        else
                        {
                            <td class="col-1">
                                Not Added
                            </td>
                        }

                        <td class="col-3">
                            @Html.DisplayFor(modelItem => item.newsCreatedDate)
                        </td>
                    </tr>
                    i = i + 1;
                }
            </table>
            <br />
            @Html.PagedListPager(Model, page => Url.Action("Index",
    new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))
        </div>
                    }
    <div id="news_information"> </div>
    <div class="extender"> </div>
</div>

SFSAcademy/SFSAcademy/Views/news/_CommentSections.cshtml
@model SFSAcademy.Models.NewsDetails

<script type="text/javascript" src="@Url.Content("~/Content/javascripts/jquery/jquery.min.js")"></script>
<script type="text/javascript" src="@Url.Content("~/Content/javascripts/jquery/jquery-ui.min.js")"></script>
<script type="text/javascript" src="@Url.Content("~/Content/javascripts/jquery/jquery-1.9.1.js")"></script>
<script type="text/javascript" src="@Url.Content("~/Content/javascripts/jquery/jquery-ui.js")"></script>
<link rel="stylesheet" href="~/Content/stylesheets/_styles/jquery-ui.css" />
<div id="comment-ui">
    <h3 id="comments-heading">Comments</h3>

    @if (Model.newsCommentCount == 0)
    {
        <span id="comments-count">No Comments</span>
    }
    else
    {
        <span id="comments-count">@Model.newsCommentCount </span>
    }

    <div id="comments-section">
        <ul id="comments-list">
            @foreach (var comment in Model.commentList)
            {
                @Html.Partial("_comment", comment)
            }
        </ul>
    </div>
    <h4 id="leave-a-comment">Leave Comment</h4>
    <form name="comments-form" id="comments-form">
        @using (Html.BeginForm("add_comment", "news", FormMethod.Post))
        {
            @Html.Hidden("newsId", Model.newsId)
            <p>
                @Html.TextArea("comments", null, 5, 110, new { @class = "form-control", @id = "txtcomments" })
                @*@Html.TextAreaFor(Model=>Model.newsComment,5, 110, new { @class = "form-control", @id = "txtcomments" })*@
                <input type="button" value="► Submit" , onclick="SaveComment()" class="edit_button user_button" />
            </p>
        }
    </form>

</div>


<script type="text/javascript">

    $(document).ready(function () {
        //alert(1);
    });
    function SaveComment() {
        debugger;
        var NewsId = $("#newsId").val();
        var comment = $("#txtcomments").val();


        $.post('/news/add_comment?newsId=' + NewsId + "&news_Comment=" + comment, function (data) {
            debugger;

            if (data != "" || data!= null) {
                $("#txtcomments").val("");
                $("#comments-section").html("");
                $("#comments-section").html(data);
                //$.get('/news/view?id=' + NewsId, function (data) {
                //});
            }
            else {
                alert(data);
            }

            /* data is the pure html returned from action method, load it to your page */
            //$('#modal-box').html(data);
            /* little fade in effect */
            //$('#modal-box').fadeIn('fast');
        });
    }



</script>

SFSAcademy/SFSAcademy/Views/news/_NewsSearchPartial.cshtml
@model SFSAcademy.NEWS
@Styles.Render("~/Content/css")
@Styles.Render("~/Content/kendo/css")
@Scripts.Render("~/bundles/modernizr")
@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/bootstrap")
@Scripts.Render("~/bundles/kendoui")
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

<div id="page-yield">
    <div id="search_add_news_area">
        <div class="news_search_add">
            <div id="news_bg">
                <form action="/" method="post" id="NewsSearchForm">

                    <ul>
                        <li>
                            <label for="">Title </label>
                            @Html.TextBoxFor(m => m.TIL, new { @id = "newsTitle", @maxlength = "30", @class ="WaterMarkTextAutomatic textbox", placeholder = "Title"})
                        </li>
                        <li>
                            <label for="">Title </label>
                            @Html.TextBoxFor(m => m.TIL, new { @id = "newsTitle", @maxlength = "30", @class = "WaterMarkTextAutomatic textbox", placeholder = "Title" })
                        </li>
                        <li>
                            <label for="">Title </label>
                            @Html.TextBoxFor(m => m.TIL, new { @id = "newsTitle", @maxlength = "30", @class = "WaterMarkTextAutomatic textbox", placeholder = "Title" })
                        </li>
                    </ul>

                    <div class="extender"></div>
                </form>
            </div>
        </div>
    </div>
</div>

SFSAcademy/SFSAcademy/Views/news/all.cshtml
@model PagedList.IPagedList<SFSAcademy.Models.NewsDetails>
@using SFSAcademy
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />
@{
    ViewBag.Title = "View All";
}

<div id="content-header">
    <img src="~/Content/images/manage_news/manage_news_logo.png" alt="News Logo">
    <h1>School News</h1>
    <h3>Latest announcement</h3>
    <div id="app-back-button">
        <a href='javascript:history.back()' onclick="return confirm('are you sure?')"><img src="~/Content/images/buttons/back.png"></a>
    </div>
</div>
<div><img src="~/Content/images/_global/header_underline_.jpg" style="width:100%"></div>
<div id="inner-tab-menu">
    <ul>
        <li>@Html.ActionLink("Add New", "Create")</li>
    </ul>
</div>

<div id="page-yield">
    <div id="search_add_news_area">
        @if (ViewBag.ErrorMessage != null)
        {
            <p class="flash-msg"> @ViewBag.ErrorMessage </p>
        }
        <div class="news_search_add">
            <div id="news_bg">
                <form name="s1form" action="" style="display:inline;">
                    @using (Html.BeginForm("Index", "news", FormMethod.Get))
                    {
                        <p>
                            @Html.TextBox("SearchString", ViewBag.CurrentFilter as string)
                            <input type="submit" value="go" />
                        </p>
                    }
                </form>
                <div class="extender2"></div>
            </div>
        </div>
        <div class="extender"></div>
    </div>

    @if (Model != null)
    {
        <div id="all_news">
            <table id="listing" align="center" width:"100%" cellpadding="1" cellspacing="1">

                <tr class="tr-head">
                    <td>
                        Sr No
                    </td>
                    <td>
                        Title
                    </td>
                    <td>
                        Author
                    </td>
                    <td>
                        Comments
                    </td>
                    <td>
                        Posted
                    </td>
                </tr>
                <tr class="tr-blank"></tr>
                @{int i = 1; }
                @foreach (var item in Model)
                {
                    string selectedRow = "tr-even";
                    if (i % 2 == 0)
                    {
                        selectedRow = "tr-odd";
                    }
                    <tr class="@selectedRow">
                        <td class="col-1">@i</td>
                        <td class="col-4">
                            @Html.ActionLink(item.newsTitle, "view", new { id = item.newsId })
                        </td>

                        <td class="col-4">
                            @Html.DisplayFor(modelItem => item.newsCreatedBy)
                        </td>

                        @if (item.newsCommentCount != 0)
                        {
                            <td class="col-1">
                                @Html.DisplayFor(modelItem => item.newsCommentCount)
                            </td>
                        }
                        else
                        {
                            <td class="col-1">
                                Not Added
                            </td>
                        }

                        <td class="col-3">
                            @Html.DisplayFor(modelItem => item.newsCreatedDate)
                        </td>
                    </tr>
                    i = i + 1;
                }
            </table>
            <br />
            @Html.PagedListPager(Model, page => Url.Action("Index",
    new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))
        </div>
                    }
    <div id="news_information"> </div>
    <div class="extender"> </div>
</div>